### ISSUE TITLE
使用52ABP.CodeGenerator时出错

### ISSUE THREAD

**Issue by wangchenghu** [52ABP/52ABP.CodeGenerator#1]
在 DtoGenerator.Logic.UI.BasicOptionsViewModel.Create(List`1 possibleProjects, String entityName, SolutionLocation likelyDtoLocation)
   在 DtoGenerator.Vsix.GenerateDtoCommand.<MenuItemCallback>d__13.MoveNext() 位置 D:\SmartToken_CodeManager\52ABP_DtoGenerator\src\52ABP_DtoGenerator\DtoGenerator.Vsix\GenerateDtoCommand.cs:行号 206
----------------------------
我安装插件后，成功运行一次，然后再用就出此错了。
重启vs2017后再试，依然不行。

**Comment by ltm0203** [comment]
方便贴下你的实体信息吗？》

**Comment by wangchenghu** [comment]
实体信息是复制你教程中的Book实体。源码是abpzero 5.0.5：
public  class Book:Entity<long>
    {
       
        [Required]
        [MaxLength(32)]
        public virtual string Name { get; set; }

        [Required]
        [MaxLength(32)]
        public virtual string Surname { get; set; }

        [MaxLength(255)]
        public virtual string EmailAddress { get; set; }
    }

**Comment by ltm0203** [comment]
我看了下，是项目的信息没有获取到。所以导致的报错，我现在还无法修复这个bug。
这个bug也比较偶发性。 我只能说麻烦你忍耐。

**Comment by wangchenghu** [comment]
OK，你费心了

**Comment by ltm0203** [comment]
目前新版本已经发布了。这个问题，已经修复了。
