### ISSUE TITLE
点击后报错

### ISSUE THREAD

**Issue by cicna** [52ABP/52ABP.CodeGenerator#11]
1、在http://aspnetboilerplate.com/Templates中ASP.NET Core 2.x中，Target Framework选.NET Core
再选Multi Page Web Application
**在Options中把（Include login, register, user, role and tenant management pages.）选项去掉，使用纯净的ABP版本**
2、在下载下来的项目中，添加一个实体，选择这个代码生成，报错

报错以下：

### 在 DtoGenerator.Logic.UI.BasicOptionsViewModel.Create(List`1 possibleProjects, String entityName, SolutionLocation likelyDtoLocation)
   在 DtoGenerator.Vsix.GenerateDtoCommand.<MenuItemCallback>d__13.MoveNext() 位置 D:\Source\repos\52ABP_DtoGenerator\src\52ABP_DtoGenerator\DtoGenerator.Vsix\GenerateDtoCommand.cs:行号 194
----------------------------

**Comment by cicna** [comment]
public class Person : Entity<long>, IHasCreationTime
    {
        /// <summary>
        /// 姓名
        /// </summary>
        [Required]
        [MaxLength(SimpleProjectConsts.MaxNameLength)]
        public string Name { get; set; }

        /// <summary>
        /// 邮箱
        /// </summary>
        [EmailAddress]
        [MaxLength(SimpleProjectConsts.MaxEmailAddressLength)]
        public string EmailAddress { get; set; }

        /// <summary>
        /// 地址信息
        /// </summary>
        [MaxLength(SimpleProjectConsts.MaxAddressLength)]
        public string Address { get; set; }

        public DateTime CreationTime { get; set; }
    }

**Comment by yihango** [comment]
更新到最新版再尝试一下？
