### ISSUE TITLE
生成的文件类型改为utf-8的

### ISSUE THREAD

**Issue by edisonlovecarol** [52ABP/52ABP.CodeGenerator#13]
赶紧把生成的文件类型改为utf-8的   现在你的备注全部是乱码

**Comment by ltm0203** [comment]
@staneee 处理下呢熊猫。

**Comment by ltm0203** [comment]
已经发布了


发自坚果 R1

edisonlove <notifications@github.com> 于 2018年8月1日 上午9:30写道：


赶紧把生成的文件类型改为utf-8的 现在你的备注全部是乱码

―
