### ISSUE TITLE
代码生成器的一点建议

### ISSUE THREAD

**Issue by henqu** [52ABP/52ABP.CodeGenerator#15]
首先非常感谢大牛，提供的代码生成器方便了很多。
下边是使用过程遇到的一些问题
1：命名重复问题
权限设置里
例如：public const string Department_CreateDepartment = "Pages.Department.CreateDepartment";
建议改成：public const string Department_Create = "Pages.Department.Create";
应用层方法也存在这个问题
例如：GetPagedArticles，直接可以用GetPaged,因为前边有类名限制着，没必要再在方法里加上类名。
2：权限文件
生成的两个权限文件，把这两个文件合成一个文件两个类扩展起来方便很多。不用两个文件来回切换。
3：生成的方法。
建议返回的实体，实体集合，最好用动态类型（dynamic）,这样会方便扩展，而且效率会高。
例如：

```
public  async  Task<PagedResultDto<ArticleListDto>> GetPagedArticles(GetArticlesInput input)
		{
		    var query = _articleRepository.GetAll();
			// TODO:根据传入的参数添加过滤条件
			var articleCount = await query.CountAsync();
			var articles = await query
					.OrderBy(input.Sorting).AsNoTracking()
					.PageBy(input)
					.ToListAsync();
				// var articleListDtos = ObjectMapper.Map<List <ArticleListDto>>(articles);
				var articleListDtos =articles.MapTo<List<ArticleListDto>>();
		
				return new PagedResultDto<ArticleListDto>(
							articleCount,
							articleListDtos
					);
		}
```
建议能改成：
```
        public async Task<PagedResultDto<dynamic>> GetPaged(GetArticlesInput input)
        {
            var query = _articleRepository.GetAll();
            // TODO:根据传入的参数添加过滤条件
            var articleCount = await query.CountAsync();
            var list= await query
                .OrderBy(input.Sorting).AsNoTracking()
                .PageBy(input).Select(u => new
                {
                    u.Id,
                    u.Content,
                    u.CreationTime,
                    u.Title,
                    u.Status, 
                    u.UserId
                })
                .ToListAsync();
            return new PagedResultDto<dynamic>(articleCount,list);
        }
```
优点：
1》方便扩展，比如要不返回那个字段，很方便的就可以注释掉字段，需要新加字段也很方便。
2》这样效率比用AutoMap要快，不必要的Dto文件可以不要了，避免程序后期新增或者减少字段时候要维护多个实体。
4：还有生成的create和edit方法，建议不要合成一个方法createoredit方法，分开由前端来决定是调用那个方法。合在一起，违反了功能单一原则，前台还是要判断写不写id，还不如直接前端定是新增还是编辑。

**Comment by ltm0203** [comment]
@henqu 非常感谢。很多东西的建设性意见特别好。
目前我也在完善这些功能。等待我发布一个新版本吧。
(*^▽^*)

**Comment by ltm0203** [comment]
目前第一个功能，已经按照方式在修改了。至于第二个和第三个。
暂时不考虑。dynamic 类型会有性能上的问题。 这个是微软当初搞出来的半成品。小型项目上可以这样玩玩。
为什么会保留如此多的DTO就是为 了让一个功能或者一个业务对应有对应的DTO。
所以更多的时候需要一开始就设计好。
当然你的dynamic 在前期开发的时候，确实不错。 但是涉及业务固化的时候，还是建议使用DTO。
