### ISSUE TITLE
ABPCodePowerTools version: 2.4.2 生成的前端页面变量名称上下不一致

### ISSUE THREAD

**Issue by coolxlc** [52ABP/52ABP.CodeGenerator#16]
![2](https://user-images.githubusercontent.com/1211869/44200963-986a8580-a17a-11e8-82ea-00fd76026bf6.jpg)

**Comment by ltm0203** [comment]
已经发布，版本号为：2.4.5 
同时，你如果有合适的前端控件模板的代码块也欢迎提交给我们。
