### ISSUE TITLE
ng-zorro前端页面部分BUG

### ISSUE THREAD

**Issue by suchasmsc** [52ABP/52ABP.CodeGenerator#17]
1、大小写问题，没有使用驼峰式命名规则，有的地方就会报错；
2、缺少某些变量的定义，例如:saving, filterText；
3、缺少`'@shared/utils/file-download.service';`
4、组件页面HTML控件placeholder本地化没有加{{}}，导致页面直接显示l("xxxxx")。

使用的版本信息：

- ABPCodePowerTools version: 2.4.10

**Comment by ltm0203** [comment]
目前已经发布了几个版本，如果还有以上的问题，还请截图指明错误的地方。感谢。

**Comment by ltm0203** [comment]
![image](https://user-images.githubusercontent.com/7875527/49004521-64eabe80-f19f-11e8-823a-d4c4c01d7174.png)
实体路径不应该为复数。
