### ISSUE TITLE
Where is the code for this?

### ISSUE THREAD

**Issue by LRomano72** [52ABP/52ABP.CodeGenerator#18]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨
Can you share the code so we can fix the issues and see implementation?
Thank you!
如果有任何问题，可在以下方式获得答案：

- https://www.52abp.com/
- QQ Group：633751348

**Comment by ltm0203** [comment]
https://marketplace.visualstudio.com/items?itemName=werltm.52ABPCodeGenerator

this url can download  , but  we  can't give you source
