### ISSUE TITLE
希望能提供一个选项，用于确定生成的方法，权限等是否包含实体名称

### ISSUE THREAD

**Issue by chrsas** [52ABP/52ABP.CodeGenerator#2]
在生成的权限代码中，比如Dealer实体，都会有`DealerAppPermissions.Dealer_CreateDealer, L("CreateDealer")`这样的权限，而我认为`Dealer_Create`就足够表达新增Dealer的意思了，而却对应的资源也可以用`Create`替代，比如几百个Entity的项目，一个Create就可以代表所有新增了。<br>
所以能增加一个是否包含实体名的配置想是再好不过了。

**Comment by ltm0203** [comment]
是的，我正在开发这个功能，后面会做的功能里面 可能某个实体，只需要生成 DTO。都有可能
目前还在细化中。 请耐心等待。

**Comment by chrsas** [comment]
好的，感谢。
