### ISSUE TITLE
属性的中文名称-建议读取displayname

### ISSUE THREAD

**Issue by henq** [52ABP/52ABP.CodeGenerator#20]
建议在代码生成的时候，能读取下displayname特性，作为名称。
    public class AbpFile : FullAuditedEntity
    {
        [DisplayName("模块")]
        [StringLength(100)]
        public string Module { get; set; }

        [DisplayName("模块Id")]
        public int ModuleId { get; set; }

        [StringLength(300)]
        [DisplayName("文件URL")]
        public string Path { get; set; }

        [StringLength(100)]
        [DisplayName("文件名称")]
        public string FileName { get; set; }

        [StringLength(500)]
        [DisplayName("备注")]
        public string Note { get; set; }
    }
生成时候，如果有displayname，则用displayname，没有再用属性名。

**Comment by ltm0203** [comment]
目前已经通过手动添加注释的情况做了处理。同时，我们很难获取对应的    [DisplayName("文件名称")]
已经不是通过微软的脚手架的方式获取的。。。
