### ISSUE TITLE
生成项目冲突，PagedAndFilteredInputDto 项目的属性Filter变成FilterText，但organizationUnitAppService部分方法没有同步

### ISSUE THREAD

**Issue by pest1999** [52ABP/52ABP.CodeGenerator#23]
原项目编译正常，使用代码生成器生成一些appservice后 application项目dtos下的 PagedAndFilteredInputDto 发生变化 属性Filter变成FilterText，造成organizationUnitAppService部分方法错误 如下代码中需手动将input.Filter更改为input.FilterText，才能编译通过。
`[AbpAuthorize(PermissionNames.Pages_Administration_OrganizationUnits_ManageUsers)]
        public async Task<PagedResultDto<NameValueDto>> FindUsers(FindUsersInput input)
        {
            var userIdsInOrganizationUnit = _userOrganizationUnitRepository.GetAll()
                .Where(uou => uou.OrganizationUnitId == input.OrganizationUnitId)
                .Select(uou => uou.UserId);

            var query = UserManager.Users
                .Where(user => !userIdsInOrganizationUnit.Contains(user.Id))
                .WhereIf(
                    !input.FilterText.IsNullOrWhiteSpace(),
                    user =>
                        user.UserName.Contains(input.FilterText)
                        user.EmailAddress.Contains(input.FilterText)
                );

            var userCount = await query.CountAsync();
            var users = await query
                .OrderBy(u => u.Name)
                .ThenBy(u => u.Surname)
                .PageBy(input)
                .ToListAsync();

            return new PagedResultDto<NameValueDto>(
                userCount,
                users.Select(user =>
                    new NameValueDto(
                        $"{user.UserName} ({user.EmailAddress})",
                        user.Id.ToString()
                    )
                ).ToList()
            );
        }
`

**Comment by yihango** [comment]
下一个版本将统一代码
