### ISSUE TITLE
修改实体类型之后生成器显示的数据类型依旧是之前的类型

### ISSUE THREAD

**Issue by fanslead** [52ABP/52ABP.CodeGenerator#24]
![l3 yy dv8 6tjl x72cemx6](https://user-images.githubusercontent.com/22066473/49205777-09147580-f3eb-11e8-92b6-7dc791356ba8.png)

首次打开生成器时实体CreationDate类型为string，关闭生成器后修改CreationDate为Datetime类型，再次打开生成器显示的数据类型依旧为string，且重启VS没有效果

**Comment by yihango** [comment]
修改或删除生成器生成的同名配置文件即可解决问题

如实体 **Book**  的配置文件名称为  **Book.json**

![image](https://user-images.githubusercontent.com/26987099/49211282-2e5cb000-f3fa-11e8-97b3-073b2ea4aeab.png)


**注 :**  生成的同名配置文件在 `52abp_code_power` 目录下

**Comment by fanslead** [comment]
建议关闭生成器后不做信息缓存，或者重新打开生成器时再去识别一次实体~~
