### ISSUE TITLE
代码生成器生成多语言上的一点建议

### ISSUE THREAD

**Issue by ystemni** [52ABP/52ABP.CodeGenerator#26]
希望生成的多语言内容上，增加实体名。
例如：

书籍表（Book）下有个书名字段（Name），代码生成器生成的多语言内容就是：
`<text name="Name"  value="书名"></text>`
但是大型项目中很多其他业务表，同样会存在Name字段，这导致我们需要同步修改多语言内容以及前端内容，比较麻烦。
建议直接生成
`<text name="BookName"  value="书名"></text>`
同时，前端多语言内容也相应修改，增加实体名

**Comment by ystemni** [comment]
对比了下我的代码，还缺少input的默认值
如果能增加诸如
`<text name="BookNameInputDesc" value="请输入书籍名称" />`
之类的，那就更好了……

**Comment by ltm0203** [comment]
已收到，近期会更新

**Comment by ltm0203** [comment]
> 对比了下我的代码，还缺少input的默认值
> 如果能增加诸如
> `<text name="BookNameInputDesc" value="请输入书籍名称" />`
> 之类的，那就更好了……

关于这个地方。你是否还有其他更多的建议呢。我想把这里的多语言内容，给完善下。
