### ISSUE TITLE
建议52abp代码生成器支持用户自定义配置

### ISSUE THREAD

**Issue by ghost** [52ABP/52ABP.CodeGenerator#27]
诸如：
  1.YoYoAbpefCoreConsts 前缀YoYoAbpef能自定义；
手动修改是可以，但是每次生成代码后都得去EntityMapper中去修改一次，就有失代码生成器的初衷了。。

**Comment by ltm0203** [comment]
YoYoAbpefCoreConsts .cs 是pro版本中提供的内置类。
