### ISSUE TITLE
生成数据库映射文件时，指定的字段长度和生成的字段长度配置有误；

### ISSUE THREAD

**Issue by ghost** [52ABP/52ABP.CodeGenerator#28]
生成数据库映射文件时，指定的字段长度和生成的字段长度配置有误；
全部生成YoYoAbpefCoreConsts.EntityLengthNames.Length64；

**Comment by ltm0203** [comment]
目前关于这块的功能，我们还没有开发。还请耐心等待。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
