### ISSUE TITLE
目前这代码生成工具是不提供源码（开源）对吧

### ISSUE THREAD

**Issue by neozhu** [52ABP/52ABP.CodeGenerator#29]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://www.52abp.com/
- QQ Group：633751348

**Comment by neozhu** [comment]
能否提供一些开发vs.net开发插件的基础知识或是案例，能让我少走一些弯路。如果可以不胜感激。

**Comment by ltm0203** [comment]
vs 扩展开发 微软的官方文档中去看吧。这个没有成体系的文章。有点小众。

**Comment by neozhu** [comment]
行,我自己研究一下,有问题希望得到你的支持

**Comment by neozhu** [comment]
哈哈,还是老外慷慨,[https://github.com/wakuflair/ABPHelper]https://github.com/wakuflair/ABPHelper 就用这个修改一下模板就能满足自己要求了;谢谢

**Comment by ltm0203** [comment]
他也是国内的。


Regards,

梁桐铭（TongMming Liang）| 52ABP | 积微循环技术部部长
Microsoft MVP.
Skilled in ASP.NET MVC,.Net Core, Web API, Angular, TypeScript
Email:ltm@ddxc.org
MP: 15828417122
Website:https://52abp.com/
 [cid:image001.jpg@01D458C8.E94AE490]

________________________________
发件人: neozhu <notifications@github.com>
发送时间: Monday, January 14, 2019 2:49:50 PM
收件人: 52ABP/52ABP.CodeGenerator
抄送: Tongming Liang(梁桐铭); State change
主题: Re: [52ABP/52ABP.CodeGenerator] 目前这代码生成工具是不提供源码（开源）对吧 (#29)


哈哈,还是老外慷慨,[https://github.com/wakuflair/ABPHelper]https://github.com/wakuflair/ABPHelper 就用这个修改一下模板就能满足自己要求了;谢谢

―

**Comment by neozhu** [comment]
ok，你们都是大师，我自己再找找资料，从简单的做起，根据定义的实体生成对应的service，repository，代码应该不难做；我以前做过mvc scaffolder 的自定义开发，但到了dotnet core的机制不同不能用，看来也只能走vs extension vsix的方式添加自己的模版代码到制定的project 目录中

**Comment by neozhu** [comment]
另外我还想问一下关于asp.net zero,如果花1500美金购买一个 licence ，三个开发，一个产品，的意思是只能发布一个产品吗，还是可以发布多个不同的产品
