### ISSUE TITLE
ng-zorro的用法即将过期，建议更新

### ISSUE THREAD

**Issue by flyfire-cn** [52ABP/52ABP.CodeGenerator#31]
[NG-ZORRO] <i class="anticon"></i> would be deprecated soon. Please use <i nz-icon type=""></i> API.
建议生成器中更换下呵。

**Comment by ltm0203** [comment]
换啥，有具体的信息吗？

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by flyfire-cn** [comment]
`[NG-ZORRO] <i class="anticon"></i> would be deprecated soon. Please use <i nz-icon type=""></i>` API.
居然被系统过滤掉了呵，重新贴上。

**Comment by ltm0203** [comment]
新版本正在开发中。
