### ISSUE TITLE
插件不支持framework版本

### ISSUE THREAD

**Issue by Sharewithyou** [52ABP/52ABP.CodeGenerator#33]
![图片](https://user-images.githubusercontent.com/23255790/55845610-2addf000-5b75-11e9-964d-4b5511442df5.png)

System.NullReferenceException: 未将对象引用设置到对象的实例。 在 DtoGenerator.Vsix.GenerateDtoCommand.MenuItemCallback(Object sender, EventArgs e) 位置 D:\Source\repos\Gitee_Code\YoyoAbpCodePowerProject\DtoGenerator.Vsix\GenerateDtoCommand.cs:行号 236

**Comment by zyg0** [comment]
更新后出现 同样问题

**Comment by ghost** [comment]
同样的问题

**Comment by ltm0203** [comment]
代码生成器不再支持，.NETFramework的版本。
