### ISSUE TITLE
vs2017 插件市场里搜索不到

### ISSUE THREAD

**Issue by OldKing-lion** [52ABP/52ABP.CodeGenerator#34]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：
![image](https://user-images.githubusercontent.com/13028615/57282819-6ae6b300-70e0-11e9-8fd6-63a2daa6fa66.png)

- https://www.52abp.com/
- QQ Group：633751348

**Comment by ltm0203** [comment]
我还不知道是什么原因造成的。

可以通过手动下载解决。
https://marketplace.visualstudio.com/items?itemName=werltm.52ABPCodeGenerator

**Comment by OldKing-lion** [comment]
可以解决，我知道什么原因了，谢谢

**Comment by ltm0203** [comment]
@lionkon1 可以说下是什么问题造成的吗。
