### ISSUE TITLE
代码生成器权限配置和领域服务中多语言问题

### ISSUE THREAD

**Issue by DrGreatWall** [52ABP/52ABP.CodeGenerator#39]
**描述错误(Describe the bug)**
代码生成器生成代码以后，在权限配置BookAuthorizationProvider和领域服务的自定义公共方法类YoyoCmsTemplateDomainServiceBase，这两个文件中的多语言关联信息有误

请尽量将错误描述的清楚而简洁。
(A clear and concise description of what the bug is.)

使用的版本信息：

- ABPCodePowerTools version:2.8.0

**重现错误信息**

告诉我们是怎么操作的

1、直接点击生成以后
2、当前上下文中不存在名称“YoyoCmsTemplateConsts”
3、实际是AppConsts文件中有LocalizationSourceName方法

错误代码：

BookAuthorizationProvider文件中
private static ILocalizableString L(string name)
{
            //现在代码生成器是如下代码
            //return new LocalizableString(name, YoYoAbpefCoreConsts.LocalizationSourceName);

            //实际这段代码应该是如下代码
            return new LocalizableString(name, AppConsts.LocalizationSourceName);
 }

YoyoCmsTemplateDomainServiceBase文件中
protected YoyoCmsTemplateDomainServiceBase()
{
            //现在代码生成器是如下代码
            //  LocalizationSourceName = YoyoCmsTemplateConsts.LocalizationSourceName;

            //实际这段代码应该是如下代码
            LocalizationSourceName = AppConsts.LocalizationSourceName;
}
```
error code
```

**Expected behavior**

**截图-Screenshots**

如果可以的话，添加截图来帮助解释你的问题。 If applicable, add screenshots to help explain your problem.

**Additional context**

**Comment by ltm0203** [comment]
非常感谢您的反馈。我会在.NET Core 3.1的版本中支持它的。
