### ISSUE TITLE
安装后在VS 2017和VS 2019中右键选择代码生成器都提示“只支持.net core /standard，不支持.net framework”

### ISSUE THREAD

**Issue by alex2788** [52ABP/52ABP.CodeGenerator#43]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://www.52abp.com/
- QQ Group：633751348

**Comment by alex2788** [comment]
但我的项目都是.net core和.net standard的

**Comment by scwyh** [comment]
我在vs2019中使用，也出现这个提示。但项目是.net core 3.1的

**Comment by ltm0203** [comment]
这个一般是EF core那层的路径没有找到。
