### ISSUE TITLE
使用代码生成器出现异常

### ISSUE THREAD

**Issue by 3368aa** [52ABP/52ABP.CodeGenerator#47]
直接在代码文件上右键调用，弹出对话框
<html><head></head><body><a hrf='https://github.com/52ABP/52ABP.CodeGenerator/issues/new'>baidu</a><br>System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 DtoGenerator.Vsix.SolutionInfoCreator.Create(Document currentSelectedDocument) 位置 C:\Code\gitlab\YoyoAbpCodePowerProject\DtoGenerator.Vsix\SolutionInfoCreator.cs:行号 270
   在 DtoGenerator.Vsix.GenerateDtoCommand.MenuItemCallback(Object sender, EventArgs e) 位置 C:\Code\gitlab\YoyoAbpCodePowerProject\DtoGenerator.Vsix\GenerateDtoCommand.cs:行号 236</body></html>

**Comment by ltm0203** [comment]
这个情况，多试试。

单元测试类库别删除。
