### ISSUE TITLE
新下载的ABP免费模板，用该生成器后“报错”

### ISSUE THREAD

**Issue by cicna** [52ABP/52ABP.CodeGenerator#8]
我从abp官网上，下载了最新的免费模板
然后在该项目中，新建一个Book.cs类。
用52ABP.CodeGenerator生成工具，出错了
有人遇到过这种情况吗？

报错信息：
在 DtoGenerator.Logic.UI.BasicOptionsViewModel.Create(List`1 possibleProjects, String entityName, SolutionLocation likelyDtoLocation)
   在 DtoGenerator.Vsix.GenerateDtoCommand.<MenuItemCallback>d__13.MoveNext() 位置 D:\CodeManager\VSTS\52ABP_DtoGenerator\src\52ABP_DtoGenerator\DtoGenerator.Vsix\GenerateDtoCommand.cs:行号 193

**Comment by Shinetaku** [comment]
我也一样

**Comment by Shinetaku** [comment]
UserLoginInfoDto这个东西不能删。折腾死我了。ABPZero里的除了这个都删掉都没问题。

**Comment by yihango** [comment]
升级到最新版试一下
